/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditLocalstorageRouteImport } from './routes/audit-localstorage'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as NotaRouteImport } from './routes/nota'
import { Route as PelangganRouteImport } from './routes/pelanggan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLocalstorageRoute = AuditLocalstorageRouteImport.update({
  id: '/audit-localstorage',
  path: '/audit-localstorage',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const NotaRoute = NotaRouteImport.update({
  id: '/nota',
  path: '/nota',
  getParentRoute: () => rootRouteImport,
} as any)
const PelangganRoute = PelangganRouteImport.update({
  id: '/pelanggan',
  path: '/pelanggan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-localstorage': typeof AuditLocalstorageRoute
  '/laporan': typeof LaporanRoute
  '/nota': typeof NotaRoute
  '/pelanggan': typeof PelangganRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-localstorage': typeof AuditLocalstorageRoute
  '/laporan': typeof LaporanRoute
  '/nota': typeof NotaRoute
  '/pelanggan': typeof PelangganRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-localstorage': typeof AuditLocalstorageRoute
  '/laporan': typeof LaporanRoute
  '/nota': typeof NotaRoute
  '/pelanggan': typeof PelangganRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/audit-localstorage' | '/laporan' | '/nota' | '/pelanggan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audit-localstorage' | '/laporan' | '/nota' | '/pelanggan'
  id:
    | '__root__'
    | '/'
    | '/audit-localstorage'
    | '/laporan'
    | '/nota'
    | '/pelanggan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLocalstorageRoute: typeof AuditLocalstorageRoute
  LaporanRoute: typeof LaporanRoute
  NotaRoute: typeof NotaRoute
  PelangganRoute: typeof PelangganRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-localstorage': {
      id: '/audit-localstorage'
      path: '/audit-localstorage'
      fullPath: '/audit-localstorage'
      preLoaderRoute: typeof AuditLocalstorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nota': {
      id: '/nota'
      path: '/nota'
      fullPath: '/nota'
      preLoaderRoute: typeof NotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelanggan': {
      id: '/pelanggan'
      path: '/pelanggan'
      fullPath: '/pelanggan'
      preLoaderRoute: typeof PelangganRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLocalstorageRoute: AuditLocalstorageRoute,
  LaporanRoute: LaporanRoute,
  NotaRoute: NotaRoute,
  PelangganRoute: PelangganRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
